---
date: "2016-04-27T00:00:00Z"
external_link: ""
image:
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
- icon: github
  icon_pack: fab
  name: github-data
  url: https://allisonhorst.github.io/palmerpenguins/
#slides: example
summary: An example of using the in-built project page.
tags:
#- Deep Learning
title: Penguins
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(kableExtra)
require(broom)
library(mgcv)
library(ggplot2)
library(wesanderson)
library(psych)
library(corrplot)
library(dplyr)
library(DT)
```

```{r, echo=FALSE}
#install.packages("palmerpenguins")
library(palmerpenguins)
kable(head(penguins, 15), caption = "Summary of Palmerpenguins dataset") %>% 
  kable_styling(bootstrap_options = c("bordered", "striped", "hover", "condensed", "responsive"), full_width = FALSE)
  #kable_material("striped") %>% 
  #kable_material_dark("striped") %>% 
  #kable_minimal("striped") %>% 
  #kable_classic_2(c("hover", "striped"), font_size = 15, html_font = "sans") %>% 
  #row_spec(2:4, italic = T, bold = T, color = "gold", background = "blue") %>% 
  #column_spec(4:8, bold = T, color = "gold", background = "blue") %>% 
  #column_spec(1:3, bold = T, background = "pink") %>% 
  #add_header_above("Palmerpenguins")
```

```{r, echo=FALSE}
library(palmerpenguins)
library(DT)
datatable(penguins)
```


```{r, echo=FALSE}
library(ggplot2)
ggplot(penguins, aes(bill_length_mm, bill_depth_mm, color = species)) + 
  geom_point()
```


